# Generated by Django 2.2 on 2020-03-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='分类名称')),
                ('isIndex', models.BooleanField(default=False, verbose_name='是否在首页')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/categories/images/%Y/%m/%d', verbose_name='分类图片')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名')),
                ('price', models.FloatField(verbose_name='原价格')),
                ('discount', models.FloatField(verbose_name='折扣价格')),
                ('short', models.CharField(max_length=32, verbose_name='商品描述')),
                ('detail', models.ImageField(upload_to='goods/detail/%Y/%m/%d/', verbose_name='商品详情')),
                ('weight', models.CharField(max_length=64, verbose_name='重量')),
                ('production', models.CharField(max_length=64, verbose_name='产地')),
                ('quantity', models.IntegerField(verbose_name='限购数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='goods.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('image', models.ImageField(default='', upload_to='goods/slide_show/%Y/%m/%d/', verbose_name='图片')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播图对应的活动',
                'verbose_name_plural': '轮播图对应的活动',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='GoodPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/image/%Y/%m/%d/', verbose_name='商品图片')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Good', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='good',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='goods.Slide', verbose_name='轮播图对应的活动'),
        ),
    ]
