# Generated by Django 2.2 on 2020-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sold_num',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
