# Generated by Django 2.2 on 2020-03-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick_name',
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
