# Generated by Django 2.2 on 2020-03-16 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operations', '0002_auto_20200312_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(default='', max_length=128, verbose_name='地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'ordering': ('-created_time',),
            },
        ),
    ]
