# Generated by Django 2.2 on 2020-03-11 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(-1, '支付失败'), (0, '待支付'), (1, '支付成功，待收货'), (2, '交易成功，待评价'), (3, '交易完成'), (4, '取消交易')], default=0, max_length=32, verbose_name='订单状态')),
                ('pay', models.CharField(choices=[(1, '支付宝'), (2, '微信')], max_length=16, verbose_name='支付方式')),
                ('order_no', models.CharField(max_length=64, verbose_name='订单号')),
                ('pay_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='交易号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('mount', models.FloatField(verbose_name='订单金额')),
                ('remark', models.CharField(max_length=512, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('score', models.IntegerField(blank=True, choices=[(0, '差'), (1, '好')], null=True, verbose_name='评分')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单中的商品',
                'verbose_name_plural': '订单中的商品',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='补充')),
                ('score', models.IntegerField(default=5, verbose_name='评分')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单评价',
                'verbose_name_plural': '订单评价',
                'ordering': ('-created',),
            },
        ),
    ]
