# Generated by Django 2.2 on 2020-03-16 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20200316_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='goods.Good', verbose_name='商品'),
        ),
    ]
