# Generated by Django 2.2 on 2020-03-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20200316_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='estate',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='house',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='', max_length=128, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=128, verbose_name='地址'),
        ),
    ]
