# Generated by Django 2.2 on 2020-03-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20200316_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='订单号'),
        ),
    ]
