# Generated by Django 2.2 on 2020-03-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20200316_0343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
