# Generated by Django 2.2 on 2020-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[(1, '支付宝'), (2, '微信')], default=1, max_length=16, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
    ]
