# Generated by Django 2.2 on 2020-03-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_auto_20200316_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_no',
            field=models.CharField(blank=True, default='1584362577', max_length=64, null=True, verbose_name='交易号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, '待收货'), (1, '已完成')], default=0, max_length=32, verbose_name='订单状态'),
        ),
    ]
