# Generated by Django 2.2 on 2020-03-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_auto_20200316_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_no',
            field=models.CharField(blank=True, default='1584362680', max_length=64, null=True, verbose_name='交易号'),
        ),
    ]
