# Generated by Django 2.2 on 2020-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_auto_20200319_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_no',
            field=models.CharField(blank=True, default='1584625788', max_length=64, null=True, verbose_name='交易号'),
        ),
    ]
